### ISSUE TITLE
validate_third_level_domain.sh

### ISSUE THREAD

**Issue by emdee-is** [metebalci/digsec#10]
It would be really Nice To Have (TM) a validate_third_level_domain.sh

I assume it could parse it as a 3 level and call validate_second_level_domain.sh for the first two, and just do the incremental on the third. 

I have a usecase that needs a validate_third_level_domain.sh to retrieve TXT.

Thanks for the great software.

**Comment by metebalci** [comment]
I may add that, but the validate_second... script is also not meant to be used directly. So it is better these scripts are written by the user of digsec.
