### ISSUE TITLE
In scripts/ make a simple testsuite.bash

### ISSUE THREAD

**Issue by emdee-is** [metebalci/digsec#5]
If you made a little testsuite bash file in scripts, you could show how it works on good sites, and there are known bad DNSSEC sites do that you could test it failing too. Even a few sites for some specific examples of what you are usually looking for would help show it's usage.

It would also test your code in case you don't like pylint :-)

Thanks for the code - it's great.

**Comment by metebalci** [comment]
The validate script is more like an integration test, just to check if code is working. I will add pylint #3 and I commented about documentation #4
