### ISSUE TITLE
Use a try:/except: to make script errors less ugly

### ISSUE THREAD

**Issue by emdee-is** [metebalci/digsec#6]
A common error is BadSignatureError: and if you get one in your scripts you get an ugly and not very useful Python traceback. 

You could change your main in scripts.py to be called ```iMain``` and add this at the bottom:
```
    return 0
def main():
    try:
        i = iMain()
    except KeyboardInterrupt:
        i = 0
    except BadSignatureError:
        # explain what's going on                                               
        print(f"BadSignatureError: {e}")
        i = 2
    except Exception as e:
        print(f"Error: {e}")
        i = 1
    return i

if __name__ == '__main__':
    sys.exit(main())
```

**Comment by metebalci** [comment]
To be honest, I am not trying to make it that much user friendly, it is not a normal user tool at the end. However, I will think about this.

**Comment by emdee-is** [comment]
It's a command-line tool so catching Keyboard error is considered normal.

Easy enough to add - I wrote the code for you :-)

You call either way.

**Comment by metebalci** [comment]
The problem is not just to add a handler to the main, but what to say to the user.

**Comment by emdee-is** [comment]
My code says to the user whatever the error says as e: f"{e}" but hides the traceback which is scary to non-Python users.

**Comment by metebalci** [comment]
Can you tell me how did you receive this exception from the command line ? This is already handled inside the code, this should not have raised to user level. If so, there is an error somewhere else.

**Comment by metebalci** [comment]
I think it is related to #3 and it should have been fixed. If this happens again, please reopen this issue or create another issue.

**Comment by emdee-is** [comment]
It was from the command line and it raised an ugly python traceback.

I've come at it a different way that lets the code raise errors and handle them in one place: https://github.com/metebalci/digsec/issues/19

If you handle them all in the code and write to stdout, you force the users of the code as a library to parse your output which may be idiosyncratic.

**Comment by metebalci** [comment]
This does not answer my question. When you report an error, you should provide all the information to regenerate the error.
Again like I said in other issues, digsec is not a library to be embedded into another code, various refactorings needed for that. It is supposed to be used as a standalone tool.
