### ISSUE TITLE
Your timeout is too short, at least for me...

### ISSUE THREAD

**Issue by emdee-is** [metebalci/digsec#8]
Your timeout is too short, at least for me. I think it's 1 second.

Either increase it globally or add a timeout=10 in ```validate_second_level_domain.sh```
on the commands that take it, in which case you demo what commands take a timeout.

**Comment by metebalci** [comment]
Never experienced timeout here but I think I should remove setting the timeout to 1, so it uses system default. If it is needed to be changed, it can be sent with +timeout= flag.

**Comment by emdee-is** [comment]
Or up it to 10 at least in case the user doesn't know what or where the system timeout is set.  I've figured out how to use this through a proxy, and it adds real time delays. 10 for me is bare minimum.

Yes you can add +timeout but it's an annoyance if it timeout out-of-the-box.

**Comment by metebalci** [comment]
Please do not close an issue if it is assigned

**Comment by metebalci** [comment]
10 is an arbitrary number as 1. so keeping it to default and if needed setting it explicitly is the established method.

**Comment by metebalci** [comment]
fixed with cbd2ec910f27fdbd7d0b4f8c7cac72d1d70a1d42

**Comment by emdee-is** [comment]
Sorry for closing it - I'll let you close them.

0.1 is an arbitrary number as 1.0 but < 10 pisses of your users if it doesn't work out-of-the-box.

**Comment by metebalci** [comment]
I didnt say 0.1 . I havent experienced any issue with 1 second, and nobody ever complained about it with 1. Normally 1 second is a lot of time for a DNS request/response. The system default timeout is probably >= 60 seconds so it will work for anybody as long as their system is working with other applications.
